describe('Document Flow', () => {
	it('Visit Local DocTrack', () => {
		cy.visit('127.0.0.1:8000')
		cy.get('input[name=username]').type('HRMO')
		cy.get('input[name=password]').type('secret')
		cy.get('button[type=submit]').click()
		cy.get('.v-card__title > .row > .v-btn').click() // create document
		cy.contains('Document Title/Subject').siblings('input').type('Feb 16 - 28 Payroll')
		cy.contains('Document Type').parent().click()
        cy.contains('Salary').parent().click()
		cy.contains('Destination Office').parent().click()
		cy.contains('Office of the Provincial Budget Officer').parent().click()
        cy.get(':nth-child(4) > :nth-child(1) > .v-input > .v-input__control > .v-input__slot > .v-select__slot > :nth-child(4) > .v-input__icon > .v-icon ').click({force: true})
		cy.contains('Sender Name').parent().type('Cypress Test')
		cy.contains('Page Count').parent().type(20)
		cy.contains('Attachment').parent().type(10)
		cy.contains('Remarks').parent().type('This is cypres yo!')
        cy.contains('Save').parent().click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('admin')
		cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('.row > :nth-child(2) > .v-btn').click() // acknowledge document
        cy.get(':nth-child(5) > :nth-child(1) > .v-input > .v-input__control > .v-input__slot')
        .click().type('High').type('{enter}')
        cy.contains('Remarks').parent().type('This is urgent, please process ASAP.')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click({multiple : true, force:true})
        cy.get('input[name=username]').type('PBOO')
        cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('td > .row > :nth-child(1) > .v-btn').click()// receive document
        cy.contains('Through').parent().click()
        cy.contains('Docket Office').parent().click()
        cy.contains('Approved by').parent().type('Head of Budget Office')
        cy.contains('Remarks').parent().type('Approved, please process ASAP. Thanks')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('td > .row > :nth-child(1) > .v-btn').click() //forward document
        cy.contains('Forwarded to').parent().click()
		cy.contains('Office of the Provincial Accountant').parent().click()
        cy.contains('Through').parent().click()
        cy.contains('Others').parent().click()
        cy.contains('Approved by').parent().type('Head of Budget office')
        cy.contains('Remarks').parent().type('LGMT, please check and process ASAP. Thank you.')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('admin')
		cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('.row > :nth-child(2) > .v-btn').click() // acknowledge document
        cy.get(':nth-child(5) > :nth-child(1) > .v-input > .v-input__control > .v-input__slot')
        .click().type('High').type('{enter}')
        cy.contains('Remarks').parent().type('Acknowledged by D.O, please process. Thank you!')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('PAA')
        cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('td > .row > :nth-child(1) > .v-btn').click() // receive document
        cy.contains('Through').parent().click()
        cy.contains('Docket Office').parent().click()
        cy.contains('Approved by').parent().type('Head of Accounting')
        cy.contains('Remarks').parent().type('LGMT, please check and process ASAP. Thanks.')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()

        cy.get('td > .row > :nth-child(1) > .v-btn').click() //forward document
        cy.contains('Forwarded to').parent().click()
		cy.contains('Office of the Provincial Treasurer').parent().click()
        cy.contains('Through').parent().click()
        cy.contains('Others').parent().click()
        cy.contains('Approved by').parent().type('Head of Account office')
        cy.contains('Remarks').parent().type('LGMT, please check and process ASAP. Thank you.')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('admin')
		cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('.row > :nth-child(2) > .v-btn').click() // acknowledge document
        cy.get(':nth-child(5) > :nth-child(1) > .v-input > .v-input__control > .v-input__slot')
        .click().type('High').type('{enter}')
        cy.contains('Remarks').parent().type('Acknowledged by D.O, please process. Thank you!')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('PTO')
        cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('td > .row > :nth-child(1) > .v-btn').click() // receive document
        cy.contains('Through').parent().click()
        cy.contains('Docket Office').parent().click()
        cy.contains('Approved by').parent().type('Head of Treasury')
        cy.contains('Remarks').parent().type('LGMT, please check and process ASAP. Thanks.')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()

        cy.get('td > .row > :nth-child(1) > .v-btn').click() //forward document
        cy.contains('Forwarded to').parent().click()
		cy.contains('Office of the Governor').parent().click()
        cy.contains('Through').parent().click()
        cy.contains('Others').parent().click()
        cy.contains('Approved by').parent().type('Head of Treasury')
        cy.contains('Remarks').parent().type('LGMT, please check and process ASAP. Thank you.')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('admin')
		cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('.row > :nth-child(2) > .v-btn').click() // acknowledge document
        cy.get(':nth-child(5) > :nth-child(1) > .v-input > .v-input__control > .v-input__slot')
        .click().type('High').type('{enter}')
        cy.contains('Remarks').parent().type('Acknowledged by D.O, please process. Thank you!')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('GO')
        cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('td > .row > :nth-child(1) > .v-btn').click() // receive document
        cy.contains('Through').parent().click()
        cy.contains('Docket Office').parent().click()
        cy.contains('Approved by').parent().type('Head of G.O')
        cy.contains('Remarks').parent().type('LGMT, please check and process ASAP. Thanks.')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()

        cy.get('td > .row > :nth-child(1) > .v-btn').click() //forward document
        cy.contains('Forwarded to').parent().click()
		cy.contains('Office of the Provincial Treasurer').parent().click()
        cy.contains('Through').parent().click()
        cy.contains('Others').parent().click()
        cy.contains('Approved by').parent().type('Head of Account office')
        cy.contains('Remarks').parent().type('LGMT, please check and process ASAP. Thank you.')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('admin')
		cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('.row > :nth-child(2) > .v-btn').click() // acknowledge document
        cy.get(':nth-child(5) > :nth-child(1) > .v-input > .v-input__control > .v-input__slot')
        .click().type('High').type('{enter}')
        cy.contains('Remarks').parent().type('Acknowledged by D.O, please process. Thank you!')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('PTO')
        cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('td > .row > :nth-child(1) > .v-btn').click() // receive document
        cy.contains('Through').parent().click()
        cy.contains('Docket Office').parent().click()
        cy.contains('Approved by').parent().type('Head of Treasury')
        cy.contains('Remarks').parent().type('LGMT, please check and process ASAP. Thanks.')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()

        cy.get('td > .row > :nth-child(1) > .v-btn').click() //forward document
        cy.contains('Forwarded to').parent().click()
		cy.contains('Office of the Governor').parent().click()
        cy.contains('Through').parent().click()
        cy.contains('Others').parent().click()
        cy.contains('Approved by').parent().type('Head of Treasury office')
        cy.contains('Remarks').parent().type('LGMT, please check and process ASAP. Thank you.')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('admin')
		cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('.row > :nth-child(2) > .v-btn').click() // acknowledge document
        cy.get(':nth-child(5) > :nth-child(1) > .v-input > .v-input__control > .v-input__slot')
        .click().type('High').type('{enter}')
        cy.contains('Remarks').parent().type('Acknowledged by D.O, please process. Thank you!')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('GO')
        cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('td > .row > :nth-child(1) > .v-btn').click() // receive document
        cy.contains('Through').parent().click()
        cy.contains('Docket Office').parent().click()
        cy.contains('Approved by').parent().type('Head of G.O')
        cy.contains('Remarks').parent().type('LGMT, please check and process ASAP. Thanks.')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()

        cy.get('td > .row > :nth-child(1) > .v-btn').click() //forward document
        cy.contains('Forwarded to').parent().click()
		cy.contains('Office of the Provincial Treasurer').parent().click()
        cy.contains('Through').parent().click()
        cy.contains('Others').parent().click()
        cy.contains('Approved by').parent().type('Head of Account office')
        cy.contains('Remarks').parent().type('LGMT, please check and process ASAP. Thank you.')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('admin')
		cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('.row > :nth-child(2) > .v-btn').click() // acknowledge document
        cy.get(':nth-child(5) > :nth-child(1) > .v-input > .v-input__control > .v-input__slot')
        .click().type('High').type('{enter}')
        cy.contains('Remarks').parent().type('Acknowledged by D.O, please process. Thank you!')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('PTO')
        cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('td > .row > :nth-child(1) > .v-btn').click() // receive document
        cy.contains('Through').parent().click()
        cy.contains('Docket Office').parent().click()
        cy.contains('Approved by').parent().type('Head of Treasury')
        cy.contains('Remarks').parent().type('LGMT, please check and process ASAP. Thanks.')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.contains('Search').siblings('input').type('Feb 16 - 28 Payroll')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()

        cy.get('td > .row > :nth-child(2) > .v-btn').click()// terminate document
        cy.contains('Approved by').parent().type('Head of Treasury')
        cy.contains('Remarks').parent().type('SAHOOOOOOOOOOOD NAAAAAAAAAAAAAAAA!')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()



	})
  })