describe('Document Flow', () => {
	it('Visit Local DocTrack', () => {
		cy.visit('127.0.0.1:8000')
		cy.get('input[name=username]').type('GO')
		cy.get('input[name=password]').type('secret')
		cy.get('button[type=submit]').click()
		cy.get('.v-card__title > .row > .v-btn').click() // create document
		cy.contains('Document Title/Subject').siblings('input').type('New Documents')
		cy.contains('Document Type').parent().click()
        cy.contains('Salary').parent().click()
		cy.contains('Destination Office').parent().click()
		cy.contains('Office of the Vice Governor').parent().click()
        cy.get(':nth-child(4) > :nth-child(1) > .v-input > .v-input__control > .v-input__slot > .v-select__slot > :nth-child(4) > .v-input__icon > .v-icon ').click({force: true})
		cy.contains('Sender Name').parent().type('Cypress test')
		cy.contains('Page Count').parent().type(20)
		cy.contains('Attachment').parent().type(10)
		cy.contains('Remarks').parent().type('This is cypres yo!')
        cy.contains('Save').parent().click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('admin')
		cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('New Documents')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('.row > :nth-child(2) > .v-btn').click() // acknowledge document
        cy.get(':nth-child(5) > :nth-child(1) > .v-input > .v-input__control > .v-input__slot')
        .click().type('High').type('{enter}')
        cy.contains('Remarks').parent().type('LGMT')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click({multiple : true, force:true})
        cy.get('input[name=username]').type('VGO')
        cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('New Documents')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('td > .row > :nth-child(1) > .v-btn').click()
        cy.contains('Through').parent().click()
        cy.contains('Docket Office').parent().click()
        cy.contains('Approved by').parent().type('Atty Paul Jazmin')
        cy.contains('Remarks').parent().type('Baka Kano to!')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('VGO')
        cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('New Documents')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('td > .row > :nth-child(1) > .v-btn').click() //forward document
        cy.contains('Forwarded by').parent().type('Docking Office').type('{enter}')
        cy.contains('Forwarded to').parent().type('Provincial Human Resource Management Office').type('{enter}')
        cy.contains('Through').parent().click()
        cy.contains('Others').parent().click()
        cy.contains('Approved by').parent().type('Atty Paul Jazmin')
        cy.contains('Remarks').parent().type('Care of Atty Paul Jazmin!')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('admin')
		cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('New Documents')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('.row > :nth-child(4) > .v-btn').click() // acknowledge document
        cy.get(':nth-child(5) > :nth-child(1) > .v-input > .v-input__control > .v-input__slot')
        .click().type('Low').type('{enter}')
        cy.contains('Remarks').parent().type('LGMT')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()
        cy.get('.v-snack__action > .v-btn').click()
        cy.get('.v-app-bar__nav-icon').click()
        cy.get('.col > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(2)').click()
        cy.get('input[name=username]').type('HRMO')
        cy.get('input[name=password]').type('secret')
        cy.get('button[type=submit]').click()
        cy.contains('Search').siblings('input').type('New Documents')
        cy.get(':nth-child(1) > :nth-child(10) > .v-icon').click()
        cy.get('.row > :nth-child(2) > .v-btn').click() // terminal document
        cy.contains('Approved by').parent().type('Atty Paul Jazmin')
        cy.contains('Remarks').parent().type('Olanaps!')
        cy.get('.my-2 > .v-btn > .v-btn__content').click()
        cy.get('.v-card__actions > :nth-child(3)').click()



	})
  })